# Generated by Django 5.0.1 on 2024-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.CharField(
                choices=[
                    ("europa", "Europe"),
                    ("afrika", "Africa"),
                    ("s_amerika", "North America"),
                    ("p_amerika", "South America"),
                    ("azija", "Asia"),
                    ("australija", "Austalia"),
                ],
                max_length=50,
            ),
        ),
    ]
